name: Query filters tests

on:
  push:
    branches:
    - main
    - releases/v1
    - releases/v2
  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - ready_for_review
  workflow_dispatch: {}

jobs:
  expected-queries:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Prepare test
      id: prepare-test
      uses: ./.github/prepare-test
      with:
        version: latest

    # Test 1
    - uses: ./../action/init
      with:
        languages: javascript
        config-file: ./.github/codeql/codeql-config-query-filters1.yml
        tools: ${{ steps.prepare-test.outputs.tools-url }}
        db-location: ${{ runner.temp }}/test1
    - uses: ./../action/analyze
      with:
        output: ${{ runner.temp }}/results
        upload-database: false
        upload: false
      env:
        TEST_MODE: true
    - name: Check Sarif
      uses: ./../action/.github/check-sarif
      with:
        sarif-file:  ${{ runner.temp }}/results/javascript.sarif
        queries-run: js/zipslip
        queries-not-run: js/path-injection
    - name: Cleanup after test
      run: rm -rf "$RUNNER_TEMP/results"

    # Test 2
    - uses: ./../action/init
      with:
        languages: javascript
        config-file: ./.github/codeql/codeql-config-query-filters2.yml
        tools: ${{ steps.prepare-test.outputs.tools-url }}
        db-location: ${{ runner.temp }}/test2
    - uses: ./../action/analyze
      with:
        output: ${{ runner.temp }}/results
        upload-database: false
        upload: false
      env:
        TEST_MODE: true
    - name: Check Sarif
      uses: ./../action/.github/check-sarif
      with:
        sarif-file:  ${{ runner.temp }}/results/javascript.sarif
        queries-run: js/zipslip,javascript/example/empty-or-one-block
        queries-not-run: js/path-injection
    - name: Cleanup after test
      run: rm -rf "$RUNNER_TEMP/results"

    # Test 3
    - uses: ./../action/init
      with:
        languages: javascript
        config-file: ./.github/codeql/codeql-config-query-filters3.yml
        tools: ${{ steps.prepare-test.outputs.tools-url }}
        db-location: ${{ runner.temp }}/test3
    - uses: ./../action/analyze
      with:
        output: ${{ runner.temp }}/results
        upload-database: false
        upload: false
      env:
        TEST_MODE: true
    - name: Check Sarif
      uses: ./../action/.github/check-sarif
      with:
        sarif-file:  ${{ runner.temp }}/results/javascript.sarif
        queries-run: js/zipslip,javascript/example/empty-or-one-block,inrepo-javascript-querypack/show-ifs
        queries-not-run: js/path-injection,complex-python-querypack/show-ifs,complex-python-querypack/foo/bar/show-ifs
    - name: Cleanup after test
      run: rm -rf "$RUNNER_TEMP/results"
