name: Test reporting a failed run
on: push

env:
  CODEQL_ACTION_UPLOAD_FAILED_SARIF: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [javascript]
    steps:
    - uses: actions/checkout@v3
    - uses: ./init
      with:
        languages: ${{ matrix.language }}
    - name: Fail
      run: exit 1
    - uses: ./analyze
      with:
        category: "/language:${{ matrix.language }}"
