name: Update release branch
on: workflow_dispatch

jobs:
  update:
    timeout-minutes: 45
    runs-on: ubuntu-latest
    if: github.repository == 'github/codeql-action'
    steps:
    - uses: actions/checkout@v2
      with:
        # Need full history so we calculate diffs
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyGithub==1.55 requests

    - name: Update git config
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions[bot]"

    - name: Update release branch
      run: |
        python .github/update-release-branch.py \
          --github-token ${{ secrets.GITHUB_TOKEN }} \
          --repository-nwo ${{ github.repository }} \
          --source-branch main \
          --target-branch v1 \
          --conductor ${GITHUB_ACTOR}
